//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public string PostContent { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
